[package]
name = "rustic-mountain-core"
version = "0.1.0"
edition = "2021"
workspace = "../"
[dependencies]
hex = "*"
lazy_static= "*"
rand = {version= "*",features=["serde"]}
getrandom = {version = "*", features = ["js"]}
serde = {version = "*", features=["derive","rc"]}
serde_json = "*"
