[package]
name = "rustic-mountain-web"
version = "0.1.0"
edition = "2021"
workspace = "../"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rustic-mountain-core = { path = "../core"}
lazy_static = "*"
console_error_panic_hook = "*"